"use client";

import { useState } from "react";
import { CodePanel } from "@/components/algorithm-lab-shared";
import { DirectionSelect, GraphDiagram, StatePills } from "@/components/graph-diagram";
import { ActionButton, ConceptGrid, EdgeListInput, ErrorMessage, LabHeading, NumberInput, TraceWorkspace } from "@/components/phase-five-shared";
import { useTracePlayback } from "@/components/use-trace-playback";
import { parseGraph, type Graph } from "@/lib/graph";
import { runBellmanFord, runDijkstra, type ShortestPathAlgorithm, type ShortestPathTrace } from "@/lib/shortest-path";
import type { Locale } from "@/lib/i18n";

const configs = {
  dijkstra: { count: 5, edges: "0 1 4\n0 2 1\n2 1 2\n1 3 1\n2 3 5\n3 4 3" },
  "bellman-ford": { count: 5, edges: "0 1 4\n0 2 5\n1 2 -2\n1 3 6\n2 3 3\n3 4 2" },
} as const;
const codes = {
  dijkstra: ["dist[source] = 0;", "priority_queue<State> pq;", "pq.push({0, source});", "while (!pq.empty()) {", "  auto [d, v] = pq.top(); pq.pop();", "  for (auto [to, w] : adj[v])", "    if (dist[to] > d + w) {", "      dist[to] = d + w; parent[to] = v;", "      pq.push({-dist[to], to});", "    }", "}"],
  "bellman-ford": ["dist[source] = 0;", "for (int pass = 1; pass < n; ++pass) {", "  bool changed = false;", "  for (auto [u, v, w] : edges)", "    if (dist[u] != INF && dist[v] > dist[u] + w) {", "      dist[v] = dist[u] + w; parent[v] = u;", "      changed = true;", "    }", "  if (!changed) break;", "}", "// one more pass detects a negative cycle"],
};
const copy = {
  vi: { vertices: "Số đỉnh", edges: "Cạnh: u v [w]", source: "Nguồn", run: "Chạy thuật toán", invalidDijkstra: "Dijkstra cần 2–10 đỉnh, cạnh hợp lệ và trọng số không âm.", invalidBellman: "Bellman–Ford cần 2–10 đỉnh và cạnh có trọng số hợp lệ.", graph: "Đồ thị", distances: "Khoảng cách", step: "Bước", code: "C++ tương ứng", negative: "Chu trình âm", noNegative: "Không có chu trình âm", relaxation: "Nới lỏng cạnh", relaxationText: "Nếu đường đi qua u tốt hơn, cập nhật dist[v] và parent[v].", invariant: "Điều kiện đúng", dijkstraInvariant: "Khi một đỉnh được chốt, khoảng cách của nó là tối ưu vì mọi trọng số đều không âm.", bellmanInvariant: "Sau lượt i, mọi đường đi ngắn nhất dùng không quá i cạnh đã được phản ánh.", complexity: "Độ phức tạp", dijkstraComplexity: "Với priority queue: O((V+E) log V), bộ nhớ O(V+E).", bellmanComplexity: "O(VE), nhưng hỗ trợ cạnh âm và phát hiện chu trình âm reachable." },
  en: { vertices: "Vertex count", edges: "Edges: u v [w]", source: "Source", run: "Run algorithm", invalidDijkstra: "Dijkstra needs 2–10 vertices, valid edges, and non-negative weights.", invalidBellman: "Bellman–Ford needs 2–10 vertices and valid weighted edges.", graph: "Graph", distances: "Distances", step: "Step", code: "Matching C++", negative: "Negative cycle", noNegative: "No negative cycle", relaxation: "Edge relaxation", relaxationText: "If the route through u is better, update dist[v] and parent[v].", invariant: "Correctness condition", dijkstraInvariant: "Once a vertex is settled, its distance is optimal because every weight is non-negative.", bellmanInvariant: "After pass i, shortest paths using at most i edges have been represented.", complexity: "Complexity", dijkstraComplexity: "With a priority queue: O((V+E) log V) time and O(V+E) memory.", bellmanComplexity: "O(VE), while supporting negative edges and reachable negative-cycle detection." },
} as const;

export function ShortestPathVisualizer({ locale, algorithm }: { locale: Locale; algorithm: ShortestPathAlgorithm }) {
  const t = copy[locale]; const config = configs[algorithm]; const defaultGraph = parseGraph(config.count, config.edges, { weighted: true, directed: true });
  const initial = algorithm === "dijkstra" ? runDijkstra(defaultGraph, 0) : runBellmanFord(defaultGraph, 0);
  const [vertexCount, setVertexCount] = useState<number>(config.count); const [edgeInput, setEdgeInput] = useState<string>(config.edges); const [source, setSource] = useState(0); const [directed, setDirected] = useState(true);
  const [graph, setGraph] = useState<Graph>(defaultGraph); const [trace, setTrace] = useState<ShortestPathTrace>(initial); const [error, setError] = useState("");
  const playback = useTracePlayback(trace.steps.length); const current = trace.steps[playback.index];
  const title = algorithm === "dijkstra" ? (locale === "vi" ? "Chốt khoảng cách với Dijkstra" : "Settle distances with Dijkstra") : (locale === "vi" ? "Nới lỏng toàn bộ với Bellman–Ford" : "Relax every edge with Bellman–Ford");
  const eyebrow = algorithm === "dijkstra" ? "DIJKSTRA LAB" : "BELLMAN–FORD LAB";
  const intro = algorithm === "dijkstra" ? (locale === "vi" ? "Chọn đỉnh gần nhất chưa xử lý và nới lỏng các cạnh đi ra." : "Choose the nearest unsettled vertex and relax its outgoing edges.") : (locale === "vi" ? "Lặp qua mọi cạnh để hỗ trợ trọng số âm và kiểm tra chu trình âm." : "Repeat over every edge to support negative weights and detect negative cycles.");
  function run() { try { const nextGraph = parseGraph(vertexCount, edgeInput, { weighted: true, directed }); const nextTrace = algorithm === "dijkstra" ? runDijkstra(nextGraph, source) : runBellmanFord(nextGraph, source); setGraph(nextGraph); setTrace(nextTrace); playback.setIndex(0); playback.setPlaying(false); setError(""); } catch { setError(algorithm === "dijkstra" ? t.invalidDijkstra : t.invalidBellman); } }
  const annotations = current.distances.map((distance) => Number.isFinite(distance) ? `d=${distance}` : "d=∞");
  const badge = playback.index === trace.steps.length - 1 && algorithm === "bellman-ford" ? (trace.hasNegativeCycle ? t.negative : t.noNegative) : undefined;
  return <section className="mt-12" aria-labelledby={`${algorithm}-lab-title`}><LabHeading eyebrow={eyebrow} title={title} intro={intro} id={`${algorithm}-lab-title`} /><div className="surface mt-8 overflow-hidden rounded-3xl"><div className="grid items-end gap-3 border-b border-[var(--line)] bg-[var(--surface)] p-4 sm:p-6 lg:grid-cols-[.5fr_1.6fr_.5fr_.7fr_auto]"><NumberInput label={t.vertices} value={vertexCount} onChange={setVertexCount} min={2} max={10} /><EdgeListInput label={t.edges} value={edgeInput} onChange={setEdgeInput} id={`${algorithm}-edges`} /><NumberInput label={t.source} value={source} onChange={setSource} min={0} max={vertexCount - 1} /><DirectionSelect locale={locale} directed={directed} onChange={setDirected} /><div className="flex items-end"><ActionButton onClick={run} primary>{t.run}</ActionButton></div></div><ErrorMessage error={error} /><TraceWorkspace locale={locale} playback={playback} count={trace.steps.length} stepLabel={t.step} message={current.message[locale]} badge={badge}><div><p className="mb-3 text-xs font-black uppercase tracking-wider text-[var(--muted)]">{t.graph}</p><div className="overflow-x-auto"><GraphDiagram graph={graph} locale={locale} activeVertices={current.activeVertex === null ? [] : [current.activeVertex]} visitedVertices={current.settled.flatMap((settled, vertex) => settled ? [vertex] : [])} activeEdgeIds={current.activeEdgeIds} selectedEdgeIds={current.parentEdgeIds.filter((edge): edge is number => edge !== null)} annotations={annotations} label={t.graph} /></div></div><StatePills label={t.distances} values={current.distances.map((distance, vertex) => `${vertex}:${Number.isFinite(distance) ? distance : "∞"}`)} /><CodePanel title={t.code} lines={codes[algorithm]} activeLine={current.codeLine} /></TraceWorkspace></div><ConceptGrid items={[[t.relaxation, t.relaxationText], [t.invariant, algorithm === "dijkstra" ? t.dijkstraInvariant : t.bellmanInvariant], [t.complexity, algorithm === "dijkstra" ? t.dijkstraComplexity : t.bellmanComplexity]]} /></section>;
}
