"use client";

import { useState } from "react";
import { CodePanel } from "@/components/algorithm-lab-shared";
import { ActionButton, ConceptGrid, ErrorMessage, LabHeading, NumberInput, TextInput, TraceWorkspace, ValueCells } from "@/components/phase-five-shared";
import { useTracePlayback } from "@/components/use-trace-playback";
import { buildSparseTable, querySparseTable, type SparseCell, type SparseTrace } from "@/lib/sparse-table";
import type { Locale } from "@/lib/i18n";

const defaults = [5, 2, 7, 1, 6, 3, 8, 4];
const code = ["vector<vector<int>> st(logn, vector<int>(n));", "st[0] = a;", "for (int k = 1; (1 << k) <= n; ++k)", "  for (int i = 0; i + (1 << k) <= n; ++i)", "    st[k][i] = min(st[k-1][i],", "                       st[k-1][i + (1 << (k-1))]);", "", "int k = floor(log2(right - left + 1));", "return min(st[k][left], st[k][right - (1 << k) + 1]);"];
const copy = {
  vi: { eyebrow: "PHÒNG THÍ NGHIỆM SPARSE TABLE", title: "Ghép các đoạn có độ dài lũy thừa hai", intro: "Tiền xử lý minimum cho mọi đoạn 2^k, rồi phủ truy vấn bằng hai khối có thể chồng nhau.", array: "Mảng tĩnh", build: "Dựng bảng", left: "Trái", right: "Phải", query: "Truy vấn min", invalid: "Nhập 2–16 số nguyên từ -99 đến 99 và đoạn hợp lệ.", source: "Mảng nguồn", table: "Các tầng st[k][i]", step: "Bước", code: "C++ tương ứng", result: "Min", static: "Dữ liệu tĩnh", staticText: "Sparse Table không hỗ trợ cập nhật hiệu quả; hãy dựng lại bảng nếu mảng thay đổi.", idempotent: "Phép toán idempotent", idempotentText: "Với min, hai khối phủ đoạn được phép chồng nhau vì min(x, x) vẫn bằng x.", complexity: "Độ phức tạp", complexityText: "Dựng bảng O(n log n), bộ nhớ O(n log n), mỗi truy vấn RMQ O(1)." },
  en: { eyebrow: "SPARSE TABLE LAB", title: "Combine power-of-two ranges", intro: "Precompute minima for every 2^k block, then cover a query with two possibly overlapping blocks.", array: "Static array", build: "Build table", left: "Left", right: "Right", query: "Query minimum", invalid: "Enter 2–16 integers from -99 through 99 and a valid range.", source: "Source array", table: "Levels st[k][i]", step: "Step", code: "Matching C++", result: "Min", static: "Static data", staticText: "Sparse Table does not support efficient updates; rebuild it when the array changes.", idempotent: "Idempotent operation", idempotentText: "For min, the two covering blocks may overlap because min(x, x) still equals x.", complexity: "Complexity", complexityText: "O(n log n) preprocessing and memory, followed by O(1) RMQ queries." },
} as const;

export function SparseTableVisualizer({ locale }: { locale: Locale }) {
  const t = copy[locale]; const initial = buildSparseTable(defaults);
  const [input, setInput] = useState(defaults.join(", ")); const [values, setValues] = useState(initial.values); const [table, setTable] = useState(initial.table);
  const [left, setLeft] = useState(1); const [right, setRight] = useState(6); const [trace, setTrace] = useState<SparseTrace>(initial); const [error, setError] = useState("");
  const playback = useTracePlayback(trace.steps.length); const current = trace.steps[playback.index];
  function begin(next: SparseTrace) { setTrace(next); playback.setIndex(0); playback.setPlaying(false); setError(""); }
  function build() { try { const next = buildSparseTable(input.split(/[\s,]+/).filter(Boolean).map(Number)); setValues(next.values); setTable(next.table); setLeft(0); setRight(next.values.length - 1); begin(next); } catch { setError(t.invalid); } }
  function query() { try { begin(querySparseTable(values, table, left, right)); } catch { setError(t.invalid); } }
  const badge = current.result === null ? undefined : `${t.result}: ${current.result}`;
  return <section className="mt-12" aria-labelledby="sparse-lab-title"><LabHeading eyebrow={t.eyebrow} title={t.title} intro={t.intro} id="sparse-lab-title" /><div className="surface mt-8 overflow-hidden rounded-3xl"><div className="grid gap-3 border-b border-[var(--line)] bg-[var(--surface)] p-4 sm:p-6 lg:grid-cols-[1.4fr_1fr]"><div className="flex items-end gap-2"><TextInput label={t.array} value={input} onChange={setInput} id="sparse-array" /><ActionButton onClick={build} primary>{t.build}</ActionButton></div><div className="grid grid-cols-3 gap-2"><NumberInput label={t.left} value={left} onChange={setLeft} min={0} max={values.length - 1} /><NumberInput label={t.right} value={right} onChange={setRight} min={0} max={values.length - 1} /><div className="flex items-end"><ActionButton onClick={query} className="w-full">{t.query}</ActionButton></div></div></div><ErrorMessage error={error} /><TraceWorkspace locale={locale} playback={playback} count={trace.steps.length} stepLabel={t.step} message={current.message[locale]} badge={badge}><div><p className="mb-3 text-xs font-black uppercase tracking-wider text-[var(--muted)]">{t.source}</p><ValueCells values={values} active={current.range ? Array.from({ length: current.range[1] - current.range[0] + 1 }, (_, index) => current.range![0] + index) : []} label="a" /></div><div><p className="mb-3 text-xs font-black uppercase tracking-wider text-[var(--muted)]">{t.table}</p><SparseGrid table={current.table} active={current.activeCells} /></div><CodePanel title={t.code} lines={code} activeLine={current.codeLine} /></TraceWorkspace></div><ConceptGrid items={[[t.static, t.staticText], [t.idempotent, t.idempotentText], [t.complexity, t.complexityText]]} /></section>;
}

function SparseGrid({ table, active }: { table: number[][]; active: SparseCell[] }) {
  return <div className="overflow-x-auto rounded-2xl border border-[var(--line)]"><table className="w-full min-w-[38rem] border-collapse font-mono text-sm"><thead><tr className="bg-[var(--surface-strong)]"><th className="p-2 text-left">k / i</th>{table[0].map((_, index) => <th key={index} className="p-2">{index}</th>)}</tr></thead><tbody>{table.map((row, level) => <tr key={level} className="border-t border-[var(--line)]"><th className="p-2 text-left text-[var(--muted)]">{level} / 2^{level}</th>{row.map((value, index) => { const highlighted = active.some(([activeLevel, activeIndex]) => activeLevel === level && activeIndex === index); return <td key={index} className={`p-2 text-center font-black ${highlighted ? "bg-[var(--accent)] text-white" : ""}`}>{Number.isNaN(value) ? "—" : value}</td>; })}</tr>)}</tbody></table></div>;
}
